get_grid_profiles:
set_grid_profile:
  fields:
    profile:
      required: true
      example: "EN 50549-1:2019 RfG E02 Netherlands:1.2.4"
      selector:
        text:
upload_grid_profile:
  fields:
    file:
      required: true
      example: "/share/grid_profiles/64d31e5868ac391817b21af1"
      selector:
        text:
enable_dpel:
  fields:
    watt:
      example: 50
      required: true
      selector:
        number:
    slew_rate:
      example: 50
      required: false
      selector:
        number:
    export_limit:
      example: false
      required: false
      selector:
        boolean:
disable_dpel:
